In [1]:
import pandas as pd
import numpy as np

In [4]:
data = {
    'Maths' :[60,55,45,40,35],
    'Science' :[54,34,75,85,69],
    'English' :[69,58,29,42,68],
}

df = pd.DataFrame(data)
df

   Maths  Science  English
0     60       54       69
1     55       34       58
2     45       75       29
3     40       85       42
4     35       69       68

In [5]:
df.mean()

Maths      47.0
Science    63.4
English    53.2
dtype: float64

In [6]:
df.mean(axis=1)

0    61.000000
1    49.000000
2    49.666667
3    55.666667
4    57.333333
dtype: float64

In [9]:
df.quantile()

Maths      45.0
Science    69.0
English    58.0
Name: 0.5, dtype: float64

In [10]:
df.min()

Maths      35
Science    34
English    29
dtype: int64

In [11]:
df.max()

Maths      60
Science    85
English    69
dtype: int64

In [12]:
df.sum()

Maths      235
Science    317
English    266
dtype: int64

In [21]:
df

   Maths  Science  English
0     60       54       69
1     55       34       58
2     45       75       29
3     40       85       42
4     35       69       68

In [20]:
df.corr()

            Maths   Science   English
Maths    1.000000 -0.725522  0.268365
Science -0.725522  1.000000 -0.528235
English  0.268365 -0.528235  1.000000