In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
data = {
    'Department' :['IT','IT','HR','FINANCE','HR','IT'],
    'Employee':['A','B','C','D','E','F'],
    'Salary':[50000,60000,65000,45000,70000,55000],
    'Expirience':[2,4,3,1,4,5]
}
df = pd.DataFrame(data)

In [11]:
df

  Department Employee  Salary  Expirience
0         IT        A   50000           2
1         IT        B   60000           4
2         HR        C   65000           3
3    FINANCE        D   45000           1
4         HR        E   70000           4
5         IT        F   55000           5

In [16]:
df.groupby('Department')

In [17]:
df.groupby('Department').mean(numeric_only=True)

             Salary  Expirience
Department
FINANCE     45000.0    1.000000
HR          67500.0    3.500000
IT          55000.0    3.666667

In [19]:
df.groupby(['Salary','Expirience']).sum()

                  Department Employee
Salary Expirience
45000  1             FINANCE        D
50000  2                  IT        A
55000  5                  IT        F
60000  4                  IT        B
65000  3                  HR        C
70000  4                  HR        E

In [20]:
df.groupby('Department',as_index=True).sum()

            Salary  Expirience
Department
FINANCE      45000           1
HR          135000           7
IT          165000          11

In [21]:
df.groupby('Department',as_index=False).sum()

  Department  Salary  Expirience
0    FINANCE   45000           1
1         HR  135000           7
2         IT  165000          11

In [24]:
df.groupby('Department',as_index=False,sort=True).sum()

  Department  Salary  Expirience
0    FINANCE   45000           1
1         HR  135000           7
2         IT  165000          11

In [25]:
df.groupby('Department',as_index=False,sort=False).sum()

  Department  Salary  Expirience
0         IT  165000          11
1         HR  135000           7
2    FINANCE   45000           1