## Concet

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df1 = pd.DataFrame({'A':[1,2],'B':[3,4]})
df2 = pd.DataFrame({'A':[5,6],'B':[7,8]})

In [5]:
pd.concat([df1,df2])

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [6]:
pd.concat([df1,df2],axis=1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [7]:
df2 = pd.DataFrame({'A':[5,6],'D':[7,8]})

In [8]:
pd.concat([df1,df2])

   A    B    D
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [9]:
pd.concat([df1,df2],axis=1)

   A  B  A  D
0  1  3  5  7
1  2  4  6  8

In [13]:
pd.concat([df1,df2],join='outer')

   A    B    D
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [12]:
pd.concat([df1,df2],join='inner')

   A
0  1
1  2
0  5
1  6

In [17]:
pd.concat([df1,df2],join='inner',ignore_index=False)

   A
0  1
1  2
0  5
1  6

In [27]:
pd.concat([df1,df2],ignore_index=False,keys=['Train',"Test"],names=['DatasetName'])

               A    B    D
DatasetName
Train       0  1  3.0  NaN
            1  2  4.0  NaN
Test        0  5  NaN  7.0
            1  6  NaN  8.0

In [31]:
df1 = pd.DataFrame({'E':[1,2],'B':[3,4]})
df2 = pd.DataFrame({'D':[5,6],'A':[7,8]})

In [32]:
pd.concat([df1,df2],ignore_index=False,keys=['Train',"Test"],names=['DatasetName'],sort=True)

                 A    B    D    E
DatasetName
Train       0  NaN  3.0  NaN  1.0
            1  NaN  4.0  NaN  2.0
Test        0  7.0  NaN  5.0  NaN
            1  8.0  NaN  6.0  NaN

In [33]:
pd.concat([df1,df2],ignore_index=False,keys=['Train',"Test"],names=['DatasetName'],sort=False)

                 E    B    D    A
DatasetName
Train       0  1.0  3.0  NaN  NaN
            1  2.0  4.0  NaN  NaN
Test        0  NaN  NaN  5.0  7.0
            1  NaN  NaN  6.0  8.0

## Merge()

In [93]:
employees = pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['A','B','C','D'],
    'dpt_aid':[10,20,10,30],
})

department = pd.DataFrame({
    'dpt_id':[10,20,40],
    'name':['HR','IT','Finance']
})

In [71]:
pd.merge(employees,department,on='dpt_id')

   emp_id name_x  dpt_id name_y
0       1      A      10     HR
1       3      C      10     HR
2       2      B      20     IT

In [72]:
pd.merge(employees,department,on='dpt_id',how='inner')

   emp_id name_x  dpt_id name_y
0       1      A      10     HR
1       3      C      10     HR
2       2      B      20     IT

In [73]:
pd.merge(employees,department,on='dpt_id',how='outer')

   emp_id name_x  dpt_id   name_y
0     1.0      A      10       HR
1     3.0      C      10       HR
2     2.0      B      20       IT
3     4.0      D      30      NaN
4     NaN    NaN      40  Finance

In [74]:
pd.merge(employees,department,on='dpt_id',how='left')

   emp_id name_x  dpt_id name_y
0       1      A      10     HR
1       2      B      20     IT
2       3      C      10     HR
3       4      D      30    NaN

In [75]:
pd.merge(employees,department,on='dpt_id',how='right')

   emp_id name_x  dpt_id   name_y
0     1.0      A      10       HR
1     3.0      C      10       HR
2     2.0      B      20       IT
3     NaN    NaN      40  Finance

In [ ]:
pd.merge(employees,department,on='dpt_id',how='right')

In [84]:
pd.merge(employees,department,left_on='dpt_aid',right_on='dpt_id',how='outer',indicator = True)

   emp_id name_x  dpt_aid  dpt_id   name_y      _merge
0     1.0      A     10.0    10.0       HR        both
1     3.0      C     10.0    10.0       HR        both
2     2.0      B     20.0    20.0       IT        both
3     4.0      D     30.0     NaN      NaN   left_only
4     NaN    NaN      NaN    40.0  Finance  right_only

In [85]:
pd.merge(employees,department,left_on='dpt_aid',right_on='dpt_id',how='outer',indicator = False)

   emp_id name_x  dpt_aid  dpt_id   name_y
0     1.0      A     10.0    10.0       HR
1     3.0      C     10.0    10.0       HR
2     2.0      B     20.0    20.0       IT
3     4.0      D     30.0     NaN      NaN
4     NaN    NaN      NaN    40.0  Finance

In [86]:
pd.merge(employees,department,left_on='dpt_aid',right_on='dpt_id',how='outer',indicator = True,sort=True)

   emp_id name_x  dpt_aid  dpt_id   name_y      _merge
0     1.0      A     10.0    10.0       HR        both
1     3.0      C     10.0    10.0       HR        both
2     2.0      B     20.0    20.0       IT        both
3     4.0      D     30.0     NaN      NaN   left_only
4     NaN    NaN      NaN    40.0  Finance  right_only

In [87]:
pd.merge(employees,department,left_on='dpt_aid',right_on='dpt_id',how='outer',indicator = True,sort=True,copy=True)

   emp_id name_x  dpt_aid  dpt_id   name_y      _merge
0     1.0      A     10.0    10.0       HR        both
1     3.0      C     10.0    10.0       HR        both
2     2.0      B     20.0    20.0       IT        both
3     4.0      D     30.0     NaN      NaN   left_only
4     NaN    NaN      NaN    40.0  Finance  right_only

In [88]:
pd.merge(employees,department,left_on='dpt_aid',right_on='dpt_id',how='outer',indicator = True,sort=True,copy=False)

   emp_id name_x  dpt_aid  dpt_id   name_y      _merge
0     1.0      A     10.0    10.0       HR        both
1     3.0      C     10.0    10.0       HR        both
2     2.0      B     20.0    20.0       IT        both
3     4.0      D     30.0     NaN      NaN   left_only
4     NaN    NaN      NaN    40.0  Finance  right_only

In [95]:
pd.merge(employees,department,left_on='dpt_aid',right_on='dpt_id',how='outer',indicator = True,sort=True,copy=False,suffixes=['_emp','_dpt'])

   emp_id name_emp  dpt_aid  dpt_id name_dpt      _merge
0     1.0        A     10.0    10.0       HR        both
1     3.0        C     10.0    10.0       HR        both
2     2.0        B     20.0    20.0       IT        both
3     4.0        D     30.0     NaN      NaN   left_only
4     NaN      NaN      NaN    40.0  Finance  right_only

In [96]:
employees = pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['A','B','C','D'],
    'dpt_id':[10,20,10,30],
})

department = pd.DataFrame({
    'dpt_id':[10,20,40],
    'name':['HR','IT','Finance']
})

In [98]:

pd.merge(employees,department,on='dpt_id',left_index=True)

   emp_id name_x  dpt_id name_y
0       1      A      10     HR
0       3      C      10     HR
1       2      B      20     IT

In [99]:
pd.merge(employees,department,on='dpt_id',left_index=False)

   emp_id name_x  dpt_id name_y
0       1      A      10     HR
1       3      C      10     HR
2       2      B      20     IT

## ASTYPE

In [111]:
employees = pd.DataFrame({
    'emp_id':['1','2','3','4'],
    'name':['A','B','C','D'],
    'dpt_id':[10,20,10,30],
})

department = pd.DataFrame({
    'dpt_id':[10,20,40],
    'name':['HR','IT','Finance']
})

In [112]:
print(employees.dtypes)

emp_id    object
name      object
dpt_id     int64
dtype: object

In [113]:
employees['emp_id'] = employees['emp_id'].astype(int)
print(employees)

   emp_id name  dpt_id
0       1    A      10
1       2    B      20
2       3    C      10
3       4    D      30

In [114]:
print(employees.dtypes)

emp_id     int32
name      object
dpt_id     int64
dtype: object

In [116]:
employees['Active']=['y','y','y','y']

In [117]:
employees

   emp_id name  dpt_id Active
0       1    A      10      y
1       2    B      20      y
2       3    C      10      y
3       4    D      30      y

In [119]:
print(employees.dtypes)

emp_id     int32
name      object
dpt_id     int64
Active    object
dtype: object

In [120]:
employees['Active'] = employees['Active'].astype(bool)
print(employees)

   emp_id name  dpt_id  Active
0       1    A      10    True
1       2    B      20    True
2       3    C      10    True
3       4    D      30    True

In [123]:
employees['name'] = employees['name'].replace('A','P')

In [124]:
employees

   emp_id name  dpt_id  Active nmae
0       1    P      10    True    P
1       2    B      20    True    B
2       3    C      10    True    C
3       4    D      30    True    D

In [129]:
employees = employees.drop('nmae', axis=1)

In [130]:
employees

   emp_id name  dpt_id  Active
0       1    P      10    True
1       2    B      20    True
2       3    C      10    True
3       4    D      30    True