In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('diabetes_unclean.csv')

In [3]:
df

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50.0,4.7,46.0,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26.0,4.5,62.0,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50.0,4.7,46.0,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50.0,4.7,46.0,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33.0,7.1,46.0,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,191,454316,M,55.0,NaN,62.0,6.8,5.3,2.0,1.0,3.5,0.9,30.1,Y
1005,192,454316,M,55.0,4.8,88.0,NaN,5.7,4.0,0.9,3.3,1.8,30.0,Y
1006,193,454316,M,62.0,6.3,82.0,6.7,5.3,2.0,1.0,3.5,NaN,30.1,Y
1007,194,454316,F,57.0,4.1,70.0,9.3,5.3,3.3,1.0,1.4,1.3,29.0,Y
1008,195,4543,f,55.0,4.1,34.0,13.9,5.4,1.6,1.6,3.1,0.7,33.0,Y

In [4]:
df.dtypes

ID             int64
No_Pation      int64
Gender        object
AGE          float64
Urea         float64
Cr           float64
HbA1c        float64
Chol         float64
TG           float64
HDL          float64
LDL          float64
VLDL         float64
BMI          float64
CLASS         object
dtype: object

In [5]:
df = df.fillna(df.mean(numeric_only=True))

In [6]:
df

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
1,735,34221,M,26.0,4.500000,62.0,4.900000,3.7,1.4,1.1,2.1,0.600000,23.0,N
2,420,47975,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
3,680,87656,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
4,504,34223,M,33.0,7.100000,46.0,4.900000,4.9,1.0,0.8,2.0,0.400000,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,191,454316,M,55.0,5.131094,62.0,6.800000,5.3,2.0,1.0,3.5,0.900000,30.1,Y
1005,192,454316,M,55.0,4.800000,88.0,8.284155,5.7,4.0,0.9,3.3,1.800000,30.0,Y
1006,193,454316,M,62.0,6.300000,82.0,6.700000,5.3,2.0,1.0,3.5,1.850595,30.1,Y
1007,194,454316,F,57.0,4.100000,70.0,9.300000,5.3,3.3,1.0,1.4,1.300000,29.0,Y
1008,195,4543,f,55.0,4.100000,34.0,13.900000,5.4,1.6,1.6,3.1,0.700000,33.0,Y

In [7]:
df.isna().sum()

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.columns

Index(['ID', 'No_Pation', 'Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG',
       'HDL', 'LDL', 'VLDL', 'BMI', 'CLASS'],
      dtype='object')

In [10]:
df['Gender'].nunique()

3

In [11]:
df['Gender'].value_counts()

Gender
M    570
F    437
f      2
Name: count, dtype: int64

In [12]:
df['Gender']=df['Gender'].replace('f','F')

In [13]:
df['Gender'].value_counts()

Gender
M    570
F    439
Name: count, dtype: int64

In [15]:
df['Gender'].unique()

array(['F', 'M'], dtype=object)

In [17]:
df

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
1,735,34221,M,26.0,4.500000,62.0,4.900000,3.7,1.4,1.1,2.1,0.600000,23.0,N
2,420,47975,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
3,680,87656,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
4,504,34223,M,33.0,7.100000,46.0,4.900000,4.9,1.0,0.8,2.0,0.400000,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,191,454316,M,55.0,5.131094,62.0,6.800000,5.3,2.0,1.0,3.5,0.900000,30.1,Y
1005,192,454316,M,55.0,4.800000,88.0,8.284155,5.7,4.0,0.9,3.3,1.800000,30.0,Y
1006,193,454316,M,62.0,6.300000,82.0,6.700000,5.3,2.0,1.0,3.5,1.850595,30.1,Y
1007,194,454316,F,57.0,4.100000,70.0,9.300000,5.3,3.3,1.0,1.4,1.300000,29.0,Y
1008,195,4543,F,55.0,4.100000,34.0,13.900000,5.4,1.6,1.6,3.1,0.700000,33.0,Y

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
df['CLASS'].unique()

array(['N', 'N ', 'P', 'Y', 'Y '], dtype=object)

In [25]:
y = df[['CLASS']]
y.shape

(1009, 1)

In [26]:
y

     CLASS
0        N
1        N
2        N
3        N
4        N
...    ...
1004    Y
1005    Y
1006    Y
1007    Y
1008    Y

[1009 rows x 1 columns]

In [30]:
x = df.drop(['ID','No_Pation','CLASS'],axis=1)

In [49]:
x

,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
0,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0
1,M,26.0,4.500000,62.0,4.900000,3.7,1.4,1.1,2.1,0.600000,23.0
2,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0
3,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0
4,M,33.0,7.100000,46.0,4.900000,4.9,1.0,0.8,2.0,0.400000,21.0
...,...,...,...,...,...,...,...,...,...,...,...
1004,M,55.0,5.131094,62.0,6.800000,5.3,2.0,1.0,3.5,0.900000,30.1
1005,M,55.0,4.800000,88.0,8.284155,5.7,4.0,0.9,3.3,1.800000,30.0
1006,M,62.0,6.300000,82.0,6.700000,5.3,2.0,1.0,3.5,1.850595,30.1
1007,F,57.0,4.100000,70.0,9.300000,5.3,3.3,1.0,1.4,1.300000,29.0
1008,F,55.0,4.100000,34.0,13.900000,5.4,1.6,1.6,3.1,0.700000,33.0

In [78]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [79]:
x_train.shape

(756, 11)

In [92]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [93]:
x_train.shape

(807, 11)

In [94]:
x_train

    Gender   AGE  Urea     Cr  HbA1c  Chol        TG  HDL  LDL  VLDL   BMI
724      M  54.0   5.4   68.0    3.0   1.2  0.700000  1.0  0.5   1.5  33.0
951      F  55.0   6.6  168.0    7.0   4.0  2.348769  1.0  2.0   1.0  33.0
837      M  53.0   3.8   59.0   10.9   5.1  3.200000  1.8  2.0   1.0  28.0
815      F  59.0   6.0   28.0   14.6   6.1  4.400000  1.2  1.3   2.0  29.0
252      F  61.0   2.1   23.0    9.9   4.1  4.200000  1.2  1.4   1.1  28.0
..     ...   ...   ...    ...    ...   ...       ...  ...  ...   ...   ...
320      M  60.0   6.5   30.0    9.0   5.9  3.400000  0.8  3.7   0.5  30.0
527      M  52.0   4.9   68.0   10.2   5.9  2.900000  1.0  3.6   1.3  39.0
996      M  31.0   3.0   60.0   12.3   4.1  2.200000  0.7  2.4  15.4  37.2
125      F  39.0   3.0   38.0    6.4   4.7  1.300000  1.1  3.1   0.6  22.0
265      F  51.0   2.1   46.0    5.9   4.1  2.700000  1.0  2.0   1.2  36.0

[807 rows x 11 columns]

In [95]:
x_test

    Gender   AGE  Urea    Cr  HbA1c  Chol    TG  HDL  LDL  VLDL   BMI
891      F  56.0   4.0  38.0    7.7   6.1   2.3  1.6  3.6   1.0  26.0
753      F  68.0   4.2  41.0   11.9   4.0   1.1  2.3  1.1   0.5  30.0
452      M  63.0   4.3  42.0    9.0   4.2   3.4  0.9  2.0   1.0  26.0
667      F  61.0   2.5  45.0   11.6   9.7  13.8  1.0  3.1   6.3  33.0
353      M  55.0   4.6  77.0    6.5   6.0   1.5  1.3  4.1   0.6  30.0
..     ...   ...   ...   ...    ...   ...   ...  ...  ...   ...   ...
31       M  47.0   4.6  55.0    4.3   4.6   0.8  0.9  4.2   4.1  24.0
315      M  54.0   5.5  69.0   11.0   6.3   6.8  0.7  2.4   3.1  29.0
193      M  40.0   4.3  72.0    7.0   4.0   1.8  0.9  2.4  12.2  40.0
384      M  77.0   6.2  99.0    7.2   3.2   1.1  0.8  2.0   0.5  29.0
307      M  55.0   3.7  93.0    7.2   3.2   1.9  0.6  1.8   0.8  30.0

[202 rows x 11 columns]

In [96]:
y_train

    CLASS
724     Y
951     Y
837     Y
815     Y
252     Y
..    ...
320     Y
527     Y
996    Y
125     P
265     Y

[807 rows x 1 columns]

In [97]:
y_test

    CLASS
891     Y
753     Y
452     Y
667     Y
353     Y
..    ...
31      N
315     Y
193     Y
384     Y
307     Y

[202 rows x 1 columns]